#!/bin/bash

FILES=$(git diff --cached --name-only --diff-filter=d | grep -E '\.(js|ts|jsx|tsx|svelte|cjs|postcss|json)$')
# If no files found, just exit
[ -z "$FILES" ] && exit 0

echo $FILES

# Check if the 'bun' command is available and set the CMD variable accordingly
if command -v bun &> /dev/null; then
    echo "Running linters with bun..."
    CMD="bunx"
else
    echo "Running linters with npm..."
    CMD="npx"
fi

# Run linters

$CMD prettier --check $FILES
if [ $? -ne 0 ]; then
    exit 1
fi

# Run eslint and exit if it fails
$CMD eslint $FILES
if [ $? -ne 0 ]; then
    exit 1
fi

# Run unit tests and exit if they fail
$CMD vitest run
if [ $? -ne 0 ]; then
    exit 1
fi

exit 0