name: PR Validation

on:
  pull_request:
    branches: 
      - main # the branch on which PRs are merged

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Run linters
      run: npm lint
    - name: Run Svelte-check
      run: npm check
    - name: Run unit tests with coverage
      run: npm run test:coverage
    - name: Run playwright tests
      run: npm run test:integration