name: PR Validation

on:
  pull_request:
    branches:
      - main # the branch on which PRs are merged
      - dev

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run linters
        run: npm run lint
      - name: Run Svelte-check
        run: npm run check
      - name: Run unit tests with coverage
        run: npm run test:coverage
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run playwright tests
        run: npm run test:integration
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
